server:
  port: 8080

logging:
  level:
    root: INFO
    org.flowable: INFO
    org.hibernate.SQL: INFO
    org.springframework.web: INFO

spring:
  datasource:
    username: admin
    password: secret
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@

flowable:
  process:
    servlet:
      # path: /process-api
      path: /api/workflow-service
  process-definition-location-prefix: classpath*:/processes/

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info, metrics, flowable
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
