server:
  port: 8080

spring:
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@
  data:
    rest:
      base-path: /api/party-service
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    username: admin
    password: secret
  jackson:
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.springframework.web: INFO
