include:
  - path: ./services/camunda/docker-compose/8.9/docker-compose-full.yaml
    env_file: ./services/camunda/docker-compose/8.9/.env

services:

  # Make sure your certificates and keys (the *.pem files in the ./certs directory) have the correct permissions -> i.e., sudo chmod 600 *.pem

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${PWD}/services/nginx/conf/ssl.conf:/etc/nginx/conf/ssl.conf"
      - "${PWD}/services/nginx/conf/nginx-default.conf.template:/etc/nginx/templates/default.conf.template"
      - "${PWD}/certs:/etc/nginx/certs"

  serendipity-storage-service:
    container_name: serendipity-storage-service
    # image: postgres:${SERENDIPITY_STORAGE_SERVICE_VERSION}
    image: percona/percona-distribution-postgresql:${SERENDIPITY_STORAGE_SERVICE_VERSION}
    restart: unless-stopped
    command: >
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/server.crt 
      -c ssl_key_file=/var/lib/postgresql/server.key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${SERENDIPITY_DB} -U $${SERENDIPITY_STORAGE_SERVICE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: ${SERENDIPITY_DB}
      POSTGRES_USER: ${SERENDIPITY_STORAGE_SERVICE_USER}
      POSTGRES_PASSWORD: ${SERENDIPITY_STORAGE_SERVICE_PASSWORD}
      PGSSLMODE: require
      ENABLE_PG_TDE: 1
    env_file:
      - "${PWD}/.env"
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${PWD}/certs/cert.pem:/var/lib/postgresql/server.crt"
      - "${PWD}/certs/key.pem:/var/lib/postgresql/server.key"
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.9.0
    ports:
      - "5443:443"
    restart: unless-stopped
    environment:
      PGADMIN_ENABLE_TLS: true
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${PWD}/certs/cert.pem:/certs/server.cert"
      - "${PWD}/certs/key.pem:/certs/server.key"
      - "${PWD}/pgadmin_data:/var/lib/pgadmin"
    depends_on:
      - serendipity-storage-service

  serendipity-party-service:
    container_name: serendipity-party-service
    build:
      context: ./modules/party-service
      dockerfile: Dockerfile
    ports:
      - "30101:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://serendipity-storage-service:5432/${SERENDIPITY_DB}
      SPRING_DATASOURCE_USERNAME: ${SERENDIPITY_STORAGE_SERVICE_USER}
      SPRING_DATASOURCE_PASSWORD: ${SERENDIPITY_STORAGE_SERVICE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${PWD}/certs/keystore.p12:/keystore/keystore.p12"
    depends_on:
      - serendipity-storage-service

  serendipity-web-bff:
    container_name: serendipity-web-bff
    build:
      context: ./modules/web-bff
      dockerfile: Dockerfile
    environment:
      PARTY_SERVICE_URI: http://serendipity-party-service:8080/api/party-service
      WORKFLOW_SERVICE_URI: http://serendipity-workflow-service:8080/api/workflow-service
    restart: unless-stopped
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - serendipity-storage-service

volumes:
  postgres_data:

networks:
  serendipity:
    name: serendipity
