services:

  identity-service-data:
    container_name: identity-service-data
    image: postgres:${SERENDIPITY_STORAGE_SERVICE_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SERENDIPITY_IDENTITY_SERVICE_DB}
      POSTGRES_USER: ${SERENDIPITY_IDENTITY_SERVICE_USER}
      POSTGRES_PASSWORD: ${SERENDIPITY_IDENTITY_SERVICE_PASSWORD}
    env_file:
      - "${PWD}/.env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${SERENDIPITY_IDENTITY_SERVICE_USER} -d $${SERENDIPITY_IDENTITY_SERVICE_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - identity_service_data:/var/lib/postgresql/data

  serendipity-identity-service:
    container_name: serendipity-identity-service
    image: quay.io/keycloak/keycloak:26.1.0
    command:
      [
        "start-dev",
        "-Dkeycloak.migration.action=export",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.realmName=${REALM_NAME:-serendipity-dev}",
        "-Dkeycloak.migration.usersExportStrategy=REALM_FILE",
        "-Dkeycloak.migration.file=/export/${REALM_NAME:-serendipity-dev}-realm.json"
      ]
    restart: unless-stopped
    environment:
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"

      # Proxy and Path Configuration
      KC_PROXY_HEADERS: "xforwarded"
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HOSTNAME: ${SERENDIPITY_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"

      # Database Connection
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://identity-service-data:5432/${SERENDIPITY_IDENTITY_SERVICE_DB}
      KC_DB_USERNAME: ${SERENDIPITY_IDENTITY_SERVICE_USER}
      KC_DB_PASSWORD: ${SERENDIPITY_IDENTITY_SERVICE_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${SERENDIPITY_IDENTITY_SERVICE_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${SERENDIPITY_IDENTITY_SERVICE_ADMIN_PASSWORD}
    env_file:
      - "${PWD}/.env"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e 'GET /auth/health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    networks:
      - serendipity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${PWD}/services/identity-service/import:/opt/keycloak/data/import/:ro"
      - "${PWD}/services/identity-service/export:/export"
    depends_on:
      identity-service-data:
        condition: service_healthy

volumes:
  identity_service_data:

networks:
  serendipity:
    name: serendipity
