# FROM bitnami/openldap:latest
FROM bitnamilegacy/openldap:latest
# FROM bitnamisecure/openldap:latest

COPY ldifs /ldifs

# See: Upcoming changes to the Bitnami catalog - https://github.com/bitnami/charts/issues/35164
# See: https://www.dockerstatus.com/
