server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.server.mvc: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: party-service-route
              uri: http://serendipity-party-service:8080/api/party-service
              predicates:
                - Path=/api/party-service/**
            - id: workflow-service-route
              uri: http://serendipity-workflow-service:8080/api/workflow-service
              predicates:
                - Path=/api/workflow-service/**
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

serendipity-bff:
  uri: https://serendipity.localhost
