serendipity-web-bff:
  auth:
    enabled: false
  uri: https://serendipity.localhost

spring:
  security:
    oauth2:
      client:
        registration:
          bff-client:
            client-id: serendipity-bff
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          bff-client:
            issuer-uri: https://serendipity-identity-service.localhost/realms/serendipity-dev

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: party-service-route
              uri: http://serendipity-party-service:8080/api/party-service
              predicates:
                - Path=/api/party-service/**
            - id: orchestration-cluster-user-tasks-service-route
              uri: http://orchestration:8080/v2/user-tasks
              predicates:
                - Path=/v2/user-tasks/**
            - id: orchestration-cluster-process-definitions-service-route
              uri: http://orchestration:8080/v2/process-definitions
              predicates:
                - Path=/v2/process-definitions/**
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.server.mvc: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
