# Shared Modern SSL/TLS Runtime Configuration

# Protocols: Only allow ultra-secure modern handshake channels
ssl_protocols TLSv1.2 TLSv1.3;

# Ciphers
ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

# Server Preference: Force the browser to use our top-tier ciphers first
ssl_prefer_server_ciphers on;

# Session Optimization: Cache handshakes to make subsequent page loads much faster
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;

# Logging Channel configuration
access_log /var/log/nginx/access.log;

# https://developers.cloudflare.com/ssl/edge-certificates/additional-options/cipher-suites/recommendations/
